In [2]:
import pandas as pd
%pip install openpyxl
%pip install --upgrade pip

Requirement already satisfied: openpyxl in /usr/local/lib/python3.11/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.11/site-packages (from openpyxl) (2.0.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pip in /usr/local/lib/python3.11/site-packages (26.2.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [3]:
#dataframe
df = pd.read_excel('data/raw/dados_cesi.xlsx')

In [4]:
df.head()

,data,cesi_global,cesi_g10,cesi_united_states,cesi_eurozone,cesi_asia_pacific,cesi_latin_america,cesi_emerging_markets,cesi_bric
0,2003-01-01,NaN,-12.3,-21.1,-21.8,26.7,20.4,23.6,19.88
1,2003-01-02,4.3,-6.1,-6.0,-22.7,20.7,20.1,20.0,19.88
2,2003-01-03,4.4,-6.2,-5.3,-24.1,20.8,20.4,20.2,19.89
3,2003-01-06,4.5,-6.3,-4.6,-28.5,20.4,21.7,20.6,20.01
4,2003-01-07,3.9,-7.4,-3.6,-31.5,20.9,21.9,20.9,19.92

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6078 entries, 0 to 6077
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   data                   6078 non-null   datetime64[ns]
 1   cesi_global            6048 non-null   float64
 2   cesi_g10               6060 non-null   float64
 3   cesi_united_states     6057 non-null   float64
 4   cesi_eurozone          6057 non-null   float64
 5   cesi_asia_pacific      6055 non-null   float64
 6   cesi_latin_america     6056 non-null   float64
 7   cesi_emerging_markets  6043 non-null   float64
 8   cesi_bric              6051 non-null   float64
dtypes: datetime64[ns](1), float64(8)
memory usage: 427.5 KB

In [6]:
#eliminando a fase experimental de 2023
df_cesi = df.set_index('data').sort_index()
df_cesi = df_cesi.loc['2004-01-01':]

df_cesi.head()

,cesi_global,cesi_g10,cesi_united_states,cesi_eurozone,cesi_asia_pacific,cesi_latin_america,cesi_emerging_markets,cesi_bric
data,,,,,,,,
2004-01-01,NaN,51.2,61.1,53.9,39.1,-39.6,18.9,11.78
2004-01-02,41.7,57.1,75.6,53.7,38.3,-38.8,18.6,11.85
2004-01-05,40.5,55.5,71.6,53.6,36.3,-36.1,18.0,12.22
2004-01-06,38.5,52.7,65.0,54.7,34.8,-35.1,17.1,12.36
2004-01-07,38.1,50.7,62.3,52.1,37.7,-34.0,19.1,12.86

In [7]:
df_etf = pd.read_excel('data/raw/yahoo_carteira_universo.xlsx', sheet_name='TLT')
df_etf['Date'] = pd.to_datetime(df_etf['Date'])
df_etf = df_etf.set_index('Date').sort_index()

df_alinhado = df_cesi.reindex(df_etf.index)

df_alinhado.head()

,cesi_global,cesi_g10,cesi_united_states,cesi_eurozone,cesi_asia_pacific,cesi_latin_america,cesi_emerging_markets,cesi_bric
Date,,,,,,,,
2002-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-08-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-08-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-08-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
print(df_alinhado.isna().sum())

cesi_global              368
cesi_g10                 377
cesi_united_states       379
cesi_eurozone            379
cesi_asia_pacific        381
cesi_latin_america       380
cesi_emerging_markets    390
cesi_bric                383
dtype: int64

In [9]:
df_limpo = df_alinhado.ffill().bfill()

In [10]:
print(df_limpo.isna().sum())

cesi_global              0
cesi_g10                 0
cesi_united_states       0
cesi_eurozone            0
cesi_asia_pacific        0
cesi_latin_america       0
cesi_emerging_markets    0
cesi_bric                0
dtype: int64

In [11]:
df_limpo.to_csv('data/processed/cesi_limpo.csv')